{{- if .Values.azureOpenAI.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  azureOpenAIKey: "{{ .Values.azureOpenAI.key }}"
  azureOpenAIEndpoint: "{{ .Values.azureOpenAI.endpoint }}"
  azureOpenAIDeploymentName: "{{ .Values.azureOpenAI.deploymentName }}"
{{- end }}
